config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = post.comments.create(comment_params)
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path(post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  # NEW -> CREATE
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.save

    # post_path(post), 즉 새로 생성된 post의 show action으로 이동한다.
    redirect_to post_path(post)
  end

  # EDIT -> UPDATE
  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      # post라는 이름의 form 에 대해서 ( form_for @post / form_for :post )
      # title, content라는 항목에 대해서만 parameter로 받는다
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FastTrackAsiaCrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div>
<%= form_for @post do |f| %>
<% # form_for :post, url: post_path(post), method: :patch do |f| %>
  <div>
    <%= f.label :title  %><br />
    <%= f.text_field :title  %><br />
  </div>

  <div>
    <%= f.label :content  %><br />
    <%= f.text_field :content  %><br />
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<%= link_to "New Post", new_post_path  %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %>
      <%= link_to "edit", edit_post_path(post) %>
      <%= link_to "destroy", post_path(post), method: :DELETE  %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div>
<%= form_for @post do |f| %>
<% # form_for :post, url: posts_path, method: :post do |f| %>
  <div>
    <%= f.label :title  %><br />
    <%= f.text_field :title  %><br />
  </div>

  <div>
    <%= f.label :content  %><br />
    <%= f.text_field :content  %><br />
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title  %></h1>
<div>
  <%= @post.content  %>
</div>

<h2>New Comment</h2>
<%= form_for :comment, url: post_comments_path(@post) do |f| %>
  <div>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>

  <div>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>

  <div>
    <%= f.submit  %>
  </div>
<% end %>

<% if @post.comments.any?  %>
  <% @post.comments.each do |comment| %>
    <li>
      <%= comment.commenter  %> : <%= comment.content  %>
      <%= link_to "delete", post_comment_path(post_id: @post, id: comment.id), method: :DELETE %>
    </li>
  <% end %>
<% else %>
  현재 등록되어 있는 댓글이 없습니다.
<% end %>